export const mockDataContacts = [
	{
		id: 1,
		name: "Aldrin Jay B. Achas",
		email: "aldrinjaylej@gmail.com",
		phone: "09955782851",
		street: "Baybay 2 G. Abogado St",
		city: "Borongan City",
		province: "Eastern Samar",
		zipCode: 6800,
	},
	{
		id: 2,
		name: "Magnus Ambot",
		email: "mockdatatest2@gmail.com",
		phone: "09955782222",
		street: "Campesao St",
		city: "Borongan City",
		province: "Eastern Samar",
		zipCode: 6800,
	},
	{
		id: 3,
		name: "Maria Tunaw",
		email: "mockdatatest3@gmail.com",
		phone: "09915782222",
		street: "Barangay Bato",
		city: "Borongan City",
		province: "Eastern Samar",
		zipCode: 6800,
	},
	{
		id: 4,
		name: "Pierce TheVeil",
		email: "mockdatatest4@gmail.com",
		phone: "09955731222",
		street: "Barangay Can-abong",
		city: "Borongan City",
		province: "Eastern Samar",
		zipCode: 6800,
	},
	{
		id: 6,
		name: "Waray Ngaran",
		email: "mockdatatest6@gmail.com",
		phone: "09955782252",
		street: "San Jose",
		city: "Borongan City",
		province: "Eastern Samar",
		zipCode: 6800,
	},
];
